/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TasksImport } from './routes/tasks'
import { Route as SigninImport } from './routes/signin'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as TasksIndexImport } from './routes/tasks/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as TasksNewImport } from './routes/tasks/new'
import { Route as TasksTaskIdImport } from './routes/tasks/$taskId'
import { Route as AdminUsersIndexImport } from './routes/admin/users/index'
import { Route as AdminTasksIndexImport } from './routes/admin/tasks/index'
import { Route as AdminUsersUserIdImport } from './routes/admin/users/$userId'
import { Route as AdminTasksNewImport } from './routes/admin/tasks/new'
import { Route as AdminTasksTaskIdImport } from './routes/admin/tasks/$taskId'

// Create/Update Routes

const TasksRoute = TasksImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TasksIndexRoute = TasksIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const TasksNewRoute = TasksNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TasksRoute,
} as any)

const TasksTaskIdRoute = TasksTaskIdImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)

const AdminUsersIndexRoute = AdminUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminTasksIndexRoute = AdminTasksIndexImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminUsersUserIdRoute = AdminUsersUserIdImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)

const AdminTasksNewRoute = AdminTasksNewImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AdminRoute,
} as any)

const AdminTasksTaskIdRoute = AdminTasksTaskIdImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksImport
      parentRoute: typeof rootRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdImport
      parentRoute: typeof TasksImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewImport
      parentRoute: typeof TasksImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexImport
      parentRoute: typeof TasksImport
    }
    '/admin/tasks/$taskId': {
      id: '/admin/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/admin/tasks/$taskId'
      preLoaderRoute: typeof AdminTasksTaskIdImport
      parentRoute: typeof AdminImport
    }
    '/admin/tasks/new': {
      id: '/admin/tasks/new'
      path: '/tasks/new'
      fullPath: '/admin/tasks/new'
      preLoaderRoute: typeof AdminTasksNewImport
      parentRoute: typeof AdminImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdImport
      parentRoute: typeof AdminImport
    }
    '/admin/tasks/': {
      id: '/admin/tasks/'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexImport
      parentRoute: typeof AdminImport
    }
  }
}

// Create and export the route tree

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTasksTaskIdRoute: typeof AdminTasksTaskIdRoute
  AdminTasksNewRoute: typeof AdminTasksNewRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminTasksTaskIdRoute: AdminTasksTaskIdRoute,
  AdminTasksNewRoute: AdminTasksNewRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksNewRoute: typeof TasksNewRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksNewRoute: TasksNewRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/signin': typeof SigninRoute
  '/tasks': typeof TasksRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/admin/': typeof AdminIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/admin': typeof AdminIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/signin': typeof SigninRoute
  '/tasks': typeof TasksRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/admin/': typeof AdminIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/signin'
    | '/tasks'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/admin/'
    | '/tasks/'
    | '/admin/tasks/$taskId'
    | '/admin/tasks/new'
    | '/admin/users/$userId'
    | '/admin/tasks'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/admin'
    | '/tasks'
    | '/admin/tasks/$taskId'
    | '/admin/tasks/new'
    | '/admin/users/$userId'
    | '/admin/tasks'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/signin'
    | '/tasks'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/admin/'
    | '/tasks/'
    | '/admin/tasks/$taskId'
    | '/admin/tasks/new'
    | '/admin/users/$userId'
    | '/admin/tasks/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  SigninRoute: typeof SigninRoute
  TasksRoute: typeof TasksRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  SigninRoute: SigninRoute,
  TasksRoute: TasksRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/signin",
        "/tasks"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/",
        "/admin/tasks/$taskId",
        "/admin/tasks/new",
        "/admin/users/$userId",
        "/admin/tasks/",
        "/admin/users/"
      ]
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/tasks": {
      "filePath": "tasks.tsx",
      "children": [
        "/tasks/$taskId",
        "/tasks/new",
        "/tasks/"
      ]
    },
    "/tasks/$taskId": {
      "filePath": "tasks/$taskId.tsx",
      "parent": "/tasks"
    },
    "/tasks/new": {
      "filePath": "tasks/new.tsx",
      "parent": "/tasks"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/tasks/": {
      "filePath": "tasks/index.tsx",
      "parent": "/tasks"
    },
    "/admin/tasks/$taskId": {
      "filePath": "admin/tasks/$taskId.tsx",
      "parent": "/admin"
    },
    "/admin/tasks/new": {
      "filePath": "admin/tasks/new.tsx",
      "parent": "/admin"
    },
    "/admin/users/$userId": {
      "filePath": "admin/users/$userId.tsx",
      "parent": "/admin"
    },
    "/admin/tasks/": {
      "filePath": "admin/tasks/index.tsx",
      "parent": "/admin"
    },
    "/admin/users/": {
      "filePath": "admin/users/index.tsx",
      "parent": "/admin"
    }
  }
}
ROUTE_MANIFEST_END */
