/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthedRouteRouteImport } from "./routes/_authed/route";
import { Route as GuestRouteRouteImport } from "./routes/_guest/route";
import { Route as HealthRouteImport } from "./routes/health";
import { Route as PrivacyRouteImport } from "./routes/privacy";
import { Route as SignoutRouteImport } from "./routes/signout";
import { Route as TermsRouteImport } from "./routes/terms";
import { Route as AuthedAdminRouteRouteImport } from "./routes/_authed/_admin/route";
import { Route as AuthedProfileRouteImport } from "./routes/_authed/profile";
import { Route as AuthedTasksRouteRouteImport } from "./routes/_authed/tasks/route";
import { Route as GuestSigninRouteImport } from "./routes/_guest/signin";
import { Route as GuestSignupRouteImport } from "./routes/_guest/signup";
import { Route as AuthedAdminAdminRouteRouteImport } from "./routes/_authed/_admin/admin/route";
import { Route as AuthedDebugStreamingSseRouteImport } from "./routes/_authed/debug/streaming-sse";
import { Route as AuthedTasksIndexRouteImport } from "./routes/_authed/tasks/index";
import { Route as AuthedTasksTaskIdRouteImport } from "./routes/_authed/tasks/$taskId";
import { Route as AuthedTasksNewRouteImport } from "./routes/_authed/tasks/new";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as ApiSseNotificationsRouteImport } from "./routes/api/sse/notifications";
import { Route as AuthedAdminAdminIndexRouteImport } from "./routes/_authed/_admin/admin/index";
import { Route as AuthedAdminDebugMonitoringRouteImport } from "./routes/_authed/_admin/debug/monitoring";
import { Route as AuthedAdminAdminEmailsWelcomeRouteImport } from "./routes/_authed/_admin/admin/emails/welcome";
import { Route as AuthedAdminAdminTasksIndexRouteImport } from "./routes/_authed/_admin/admin/tasks/index";
import { Route as AuthedAdminAdminTasksTaskIdRouteImport } from "./routes/_authed/_admin/admin/tasks/$taskId";
import { Route as AuthedAdminAdminTasksNewRouteImport } from "./routes/_authed/_admin/admin/tasks/new";
import { Route as AuthedAdminAdminUsersIndexRouteImport } from "./routes/_authed/_admin/admin/users/index";
import { Route as AuthedAdminAdminUsersUserIdRouteImport } from "./routes/_authed/_admin/admin/users/$userId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any);
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: "/_guest",
  getParentRoute: () => rootRouteImport,
} as any);
const HealthRoute = HealthRouteImport.update({
  id: "/health",
  path: "/health",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any);
const SignoutRoute = SignoutRouteImport.update({
  id: "/signout",
  path: "/signout",
  getParentRoute: () => rootRouteImport,
} as any);
const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: "/_admin",
  getParentRoute: () => AuthedRouteRoute,
} as any);
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthedRouteRoute,
} as any);
const AuthedTasksRouteRoute = AuthedTasksRouteRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => AuthedRouteRoute,
} as any);
const GuestSigninRoute = GuestSigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => GuestRouteRoute,
} as any);
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => GuestRouteRoute,
} as any);
const AuthedAdminAdminRouteRoute = AuthedAdminAdminRouteRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => AuthedAdminRouteRoute,
} as any);
const AuthedDebugStreamingSseRoute = AuthedDebugStreamingSseRouteImport.update({
  id: "/debug/streaming-sse",
  path: "/debug/streaming-sse",
  getParentRoute: () => AuthedRouteRoute,
} as any);
const AuthedTasksIndexRoute = AuthedTasksIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedTasksRouteRoute,
} as any);
const AuthedTasksTaskIdRoute = AuthedTasksTaskIdRouteImport.update({
  id: "/$taskId",
  path: "/$taskId",
  getParentRoute: () => AuthedTasksRouteRoute,
} as any);
const AuthedTasksNewRoute = AuthedTasksNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => AuthedTasksRouteRoute,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSseNotificationsRoute = ApiSseNotificationsRouteImport.update({
  id: "/api/sse/notifications",
  path: "/api/sse/notifications",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedAdminAdminIndexRoute = AuthedAdminAdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedAdminAdminRouteRoute,
} as any);
const AuthedAdminDebugMonitoringRoute =
  AuthedAdminDebugMonitoringRouteImport.update({
    id: "/debug/monitoring",
    path: "/debug/monitoring",
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any);
const AuthedAdminAdminEmailsWelcomeRoute =
  AuthedAdminAdminEmailsWelcomeRouteImport.update({
    id: "/emails/welcome",
    path: "/emails/welcome",
    getParentRoute: () => AuthedAdminAdminRouteRoute,
  } as any);
const AuthedAdminAdminTasksIndexRoute =
  AuthedAdminAdminTasksIndexRouteImport.update({
    id: "/tasks/",
    path: "/tasks/",
    getParentRoute: () => AuthedAdminAdminRouteRoute,
  } as any);
const AuthedAdminAdminTasksTaskIdRoute =
  AuthedAdminAdminTasksTaskIdRouteImport.update({
    id: "/tasks/$taskId",
    path: "/tasks/$taskId",
    getParentRoute: () => AuthedAdminAdminRouteRoute,
  } as any);
const AuthedAdminAdminTasksNewRoute =
  AuthedAdminAdminTasksNewRouteImport.update({
    id: "/tasks/new",
    path: "/tasks/new",
    getParentRoute: () => AuthedAdminAdminRouteRoute,
  } as any);
const AuthedAdminAdminUsersIndexRoute =
  AuthedAdminAdminUsersIndexRouteImport.update({
    id: "/users/",
    path: "/users/",
    getParentRoute: () => AuthedAdminAdminRouteRoute,
  } as any);
const AuthedAdminAdminUsersUserIdRoute =
  AuthedAdminAdminUsersUserIdRouteImport.update({
    id: "/users/$userId",
    path: "/users/$userId",
    getParentRoute: () => AuthedAdminAdminRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/health": typeof HealthRoute;
  "/privacy": typeof PrivacyRoute;
  "/signout": typeof SignoutRoute;
  "/terms": typeof TermsRoute;
  "/tasks": typeof AuthedTasksRouteRouteWithChildren;
  "/profile": typeof AuthedProfileRoute;
  "/signin": typeof GuestSigninRoute;
  "/signup": typeof GuestSignupRoute;
  "/admin": typeof AuthedAdminAdminRouteRouteWithChildren;
  "/debug/streaming-sse": typeof AuthedDebugStreamingSseRoute;
  "/tasks/$taskId": typeof AuthedTasksTaskIdRoute;
  "/tasks/new": typeof AuthedTasksNewRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/sse/notifications": typeof ApiSseNotificationsRoute;
  "/tasks/": typeof AuthedTasksIndexRoute;
  "/debug/monitoring": typeof AuthedAdminDebugMonitoringRoute;
  "/admin/": typeof AuthedAdminAdminIndexRoute;
  "/admin/emails/welcome": typeof AuthedAdminAdminEmailsWelcomeRoute;
  "/admin/tasks/$taskId": typeof AuthedAdminAdminTasksTaskIdRoute;
  "/admin/tasks/new": typeof AuthedAdminAdminTasksNewRoute;
  "/admin/users/$userId": typeof AuthedAdminAdminUsersUserIdRoute;
  "/admin/tasks/": typeof AuthedAdminAdminTasksIndexRoute;
  "/admin/users/": typeof AuthedAdminAdminUsersIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/health": typeof HealthRoute;
  "/privacy": typeof PrivacyRoute;
  "/signout": typeof SignoutRoute;
  "/terms": typeof TermsRoute;
  "/profile": typeof AuthedProfileRoute;
  "/signin": typeof GuestSigninRoute;
  "/signup": typeof GuestSignupRoute;
  "/debug/streaming-sse": typeof AuthedDebugStreamingSseRoute;
  "/tasks/$taskId": typeof AuthedTasksTaskIdRoute;
  "/tasks/new": typeof AuthedTasksNewRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/sse/notifications": typeof ApiSseNotificationsRoute;
  "/tasks": typeof AuthedTasksIndexRoute;
  "/debug/monitoring": typeof AuthedAdminDebugMonitoringRoute;
  "/admin": typeof AuthedAdminAdminIndexRoute;
  "/admin/emails/welcome": typeof AuthedAdminAdminEmailsWelcomeRoute;
  "/admin/tasks/$taskId": typeof AuthedAdminAdminTasksTaskIdRoute;
  "/admin/tasks/new": typeof AuthedAdminAdminTasksNewRoute;
  "/admin/users/$userId": typeof AuthedAdminAdminUsersUserIdRoute;
  "/admin/tasks": typeof AuthedAdminAdminTasksIndexRoute;
  "/admin/users": typeof AuthedAdminAdminUsersIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authed": typeof AuthedRouteRouteWithChildren;
  "/_guest": typeof GuestRouteRouteWithChildren;
  "/health": typeof HealthRoute;
  "/privacy": typeof PrivacyRoute;
  "/signout": typeof SignoutRoute;
  "/terms": typeof TermsRoute;
  "/_authed/_admin": typeof AuthedAdminRouteRouteWithChildren;
  "/_authed/tasks": typeof AuthedTasksRouteRouteWithChildren;
  "/_authed/profile": typeof AuthedProfileRoute;
  "/_guest/signin": typeof GuestSigninRoute;
  "/_guest/signup": typeof GuestSignupRoute;
  "/_authed/_admin/admin": typeof AuthedAdminAdminRouteRouteWithChildren;
  "/_authed/debug/streaming-sse": typeof AuthedDebugStreamingSseRoute;
  "/_authed/tasks/$taskId": typeof AuthedTasksTaskIdRoute;
  "/_authed/tasks/new": typeof AuthedTasksNewRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/sse/notifications": typeof ApiSseNotificationsRoute;
  "/_authed/tasks/": typeof AuthedTasksIndexRoute;
  "/_authed/_admin/debug/monitoring": typeof AuthedAdminDebugMonitoringRoute;
  "/_authed/_admin/admin/": typeof AuthedAdminAdminIndexRoute;
  "/_authed/_admin/admin/emails/welcome": typeof AuthedAdminAdminEmailsWelcomeRoute;
  "/_authed/_admin/admin/tasks/$taskId": typeof AuthedAdminAdminTasksTaskIdRoute;
  "/_authed/_admin/admin/tasks/new": typeof AuthedAdminAdminTasksNewRoute;
  "/_authed/_admin/admin/users/$userId": typeof AuthedAdminAdminUsersUserIdRoute;
  "/_authed/_admin/admin/tasks/": typeof AuthedAdminAdminTasksIndexRoute;
  "/_authed/_admin/admin/users/": typeof AuthedAdminAdminUsersIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/health"
    | "/privacy"
    | "/signout"
    | "/terms"
    | "/tasks"
    | "/profile"
    | "/signin"
    | "/signup"
    | "/admin"
    | "/debug/streaming-sse"
    | "/tasks/$taskId"
    | "/tasks/new"
    | "/api/auth/$"
    | "/api/sse/notifications"
    | "/tasks/"
    | "/debug/monitoring"
    | "/admin/"
    | "/admin/emails/welcome"
    | "/admin/tasks/$taskId"
    | "/admin/tasks/new"
    | "/admin/users/$userId"
    | "/admin/tasks/"
    | "/admin/users/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/health"
    | "/privacy"
    | "/signout"
    | "/terms"
    | "/profile"
    | "/signin"
    | "/signup"
    | "/debug/streaming-sse"
    | "/tasks/$taskId"
    | "/tasks/new"
    | "/api/auth/$"
    | "/api/sse/notifications"
    | "/tasks"
    | "/debug/monitoring"
    | "/admin"
    | "/admin/emails/welcome"
    | "/admin/tasks/$taskId"
    | "/admin/tasks/new"
    | "/admin/users/$userId"
    | "/admin/tasks"
    | "/admin/users";
  id:
    | "__root__"
    | "/"
    | "/_authed"
    | "/_guest"
    | "/health"
    | "/privacy"
    | "/signout"
    | "/terms"
    | "/_authed/_admin"
    | "/_authed/tasks"
    | "/_authed/profile"
    | "/_guest/signin"
    | "/_guest/signup"
    | "/_authed/_admin/admin"
    | "/_authed/debug/streaming-sse"
    | "/_authed/tasks/$taskId"
    | "/_authed/tasks/new"
    | "/api/auth/$"
    | "/api/sse/notifications"
    | "/_authed/tasks/"
    | "/_authed/_admin/debug/monitoring"
    | "/_authed/_admin/admin/"
    | "/_authed/_admin/admin/emails/welcome"
    | "/_authed/_admin/admin/tasks/$taskId"
    | "/_authed/_admin/admin/tasks/new"
    | "/_authed/_admin/admin/users/$userId"
    | "/_authed/_admin/admin/tasks/"
    | "/_authed/_admin/admin/users/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren;
  GuestRouteRoute: typeof GuestRouteRouteWithChildren;
  HealthRoute: typeof HealthRoute;
  PrivacyRoute: typeof PrivacyRoute;
  SignoutRoute: typeof SignoutRoute;
  TermsRoute: typeof TermsRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiSseNotificationsRoute: typeof ApiSseNotificationsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_guest": {
      id: "/_guest";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof GuestRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/health": {
      id: "/health";
      path: "/health";
      fullPath: "/health";
      preLoaderRoute: typeof HealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy": {
      id: "/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signout": {
      id: "/signout";
      path: "/signout";
      fullPath: "/signout";
      preLoaderRoute: typeof SignoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/terms": {
      id: "/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof TermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/_admin": {
      id: "/_authed/_admin";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedAdminRouteRouteImport;
      parentRoute: typeof AuthedRouteRoute;
    };
    "/_authed/profile": {
      id: "/_authed/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof AuthedProfileRouteImport;
      parentRoute: typeof AuthedRouteRoute;
    };
    "/_authed/tasks": {
      id: "/_authed/tasks";
      path: "/tasks";
      fullPath: "/tasks";
      preLoaderRoute: typeof AuthedTasksRouteRouteImport;
      parentRoute: typeof AuthedRouteRoute;
    };
    "/_guest/signin": {
      id: "/_guest/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof GuestSigninRouteImport;
      parentRoute: typeof GuestRouteRoute;
    };
    "/_guest/signup": {
      id: "/_guest/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof GuestSignupRouteImport;
      parentRoute: typeof GuestRouteRoute;
    };
    "/_authed/_admin/admin": {
      id: "/_authed/_admin/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AuthedAdminAdminRouteRouteImport;
      parentRoute: typeof AuthedAdminRouteRoute;
    };
    "/_authed/debug/streaming-sse": {
      id: "/_authed/debug/streaming-sse";
      path: "/debug/streaming-sse";
      fullPath: "/debug/streaming-sse";
      preLoaderRoute: typeof AuthedDebugStreamingSseRouteImport;
      parentRoute: typeof AuthedRouteRoute;
    };
    "/_authed/tasks/": {
      id: "/_authed/tasks/";
      path: "/";
      fullPath: "/tasks/";
      preLoaderRoute: typeof AuthedTasksIndexRouteImport;
      parentRoute: typeof AuthedTasksRouteRoute;
    };
    "/_authed/tasks/$taskId": {
      id: "/_authed/tasks/$taskId";
      path: "/$taskId";
      fullPath: "/tasks/$taskId";
      preLoaderRoute: typeof AuthedTasksTaskIdRouteImport;
      parentRoute: typeof AuthedTasksRouteRoute;
    };
    "/_authed/tasks/new": {
      id: "/_authed/tasks/new";
      path: "/new";
      fullPath: "/tasks/new";
      preLoaderRoute: typeof AuthedTasksNewRouteImport;
      parentRoute: typeof AuthedTasksRouteRoute;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/sse/notifications": {
      id: "/api/sse/notifications";
      path: "/api/sse/notifications";
      fullPath: "/api/sse/notifications";
      preLoaderRoute: typeof ApiSseNotificationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/_admin/admin/": {
      id: "/_authed/_admin/admin/";
      path: "/";
      fullPath: "/admin/";
      preLoaderRoute: typeof AuthedAdminAdminIndexRouteImport;
      parentRoute: typeof AuthedAdminAdminRouteRoute;
    };
    "/_authed/_admin/debug/monitoring": {
      id: "/_authed/_admin/debug/monitoring";
      path: "/debug/monitoring";
      fullPath: "/debug/monitoring";
      preLoaderRoute: typeof AuthedAdminDebugMonitoringRouteImport;
      parentRoute: typeof AuthedAdminRouteRoute;
    };
    "/_authed/_admin/admin/emails/welcome": {
      id: "/_authed/_admin/admin/emails/welcome";
      path: "/emails/welcome";
      fullPath: "/admin/emails/welcome";
      preLoaderRoute: typeof AuthedAdminAdminEmailsWelcomeRouteImport;
      parentRoute: typeof AuthedAdminAdminRouteRoute;
    };
    "/_authed/_admin/admin/tasks/": {
      id: "/_authed/_admin/admin/tasks/";
      path: "/tasks";
      fullPath: "/admin/tasks/";
      preLoaderRoute: typeof AuthedAdminAdminTasksIndexRouteImport;
      parentRoute: typeof AuthedAdminAdminRouteRoute;
    };
    "/_authed/_admin/admin/tasks/$taskId": {
      id: "/_authed/_admin/admin/tasks/$taskId";
      path: "/tasks/$taskId";
      fullPath: "/admin/tasks/$taskId";
      preLoaderRoute: typeof AuthedAdminAdminTasksTaskIdRouteImport;
      parentRoute: typeof AuthedAdminAdminRouteRoute;
    };
    "/_authed/_admin/admin/tasks/new": {
      id: "/_authed/_admin/admin/tasks/new";
      path: "/tasks/new";
      fullPath: "/admin/tasks/new";
      preLoaderRoute: typeof AuthedAdminAdminTasksNewRouteImport;
      parentRoute: typeof AuthedAdminAdminRouteRoute;
    };
    "/_authed/_admin/admin/users/": {
      id: "/_authed/_admin/admin/users/";
      path: "/users";
      fullPath: "/admin/users/";
      preLoaderRoute: typeof AuthedAdminAdminUsersIndexRouteImport;
      parentRoute: typeof AuthedAdminAdminRouteRoute;
    };
    "/_authed/_admin/admin/users/$userId": {
      id: "/_authed/_admin/admin/users/$userId";
      path: "/users/$userId";
      fullPath: "/admin/users/$userId";
      preLoaderRoute: typeof AuthedAdminAdminUsersUserIdRouteImport;
      parentRoute: typeof AuthedAdminAdminRouteRoute;
    };
  }
}

interface AuthedAdminAdminRouteRouteChildren {
  AuthedAdminAdminIndexRoute: typeof AuthedAdminAdminIndexRoute;
  AuthedAdminAdminEmailsWelcomeRoute: typeof AuthedAdminAdminEmailsWelcomeRoute;
  AuthedAdminAdminTasksTaskIdRoute: typeof AuthedAdminAdminTasksTaskIdRoute;
  AuthedAdminAdminTasksNewRoute: typeof AuthedAdminAdminTasksNewRoute;
  AuthedAdminAdminUsersUserIdRoute: typeof AuthedAdminAdminUsersUserIdRoute;
  AuthedAdminAdminTasksIndexRoute: typeof AuthedAdminAdminTasksIndexRoute;
  AuthedAdminAdminUsersIndexRoute: typeof AuthedAdminAdminUsersIndexRoute;
}

const AuthedAdminAdminRouteRouteChildren: AuthedAdminAdminRouteRouteChildren = {
  AuthedAdminAdminIndexRoute: AuthedAdminAdminIndexRoute,
  AuthedAdminAdminEmailsWelcomeRoute: AuthedAdminAdminEmailsWelcomeRoute,
  AuthedAdminAdminTasksTaskIdRoute: AuthedAdminAdminTasksTaskIdRoute,
  AuthedAdminAdminTasksNewRoute: AuthedAdminAdminTasksNewRoute,
  AuthedAdminAdminUsersUserIdRoute: AuthedAdminAdminUsersUserIdRoute,
  AuthedAdminAdminTasksIndexRoute: AuthedAdminAdminTasksIndexRoute,
  AuthedAdminAdminUsersIndexRoute: AuthedAdminAdminUsersIndexRoute,
};

const AuthedAdminAdminRouteRouteWithChildren =
  AuthedAdminAdminRouteRoute._addFileChildren(
    AuthedAdminAdminRouteRouteChildren,
  );

interface AuthedAdminRouteRouteChildren {
  AuthedAdminAdminRouteRoute: typeof AuthedAdminAdminRouteRouteWithChildren;
  AuthedAdminDebugMonitoringRoute: typeof AuthedAdminDebugMonitoringRoute;
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminAdminRouteRoute: AuthedAdminAdminRouteRouteWithChildren,
  AuthedAdminDebugMonitoringRoute: AuthedAdminDebugMonitoringRoute,
};

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren);

interface AuthedTasksRouteRouteChildren {
  AuthedTasksTaskIdRoute: typeof AuthedTasksTaskIdRoute;
  AuthedTasksNewRoute: typeof AuthedTasksNewRoute;
  AuthedTasksIndexRoute: typeof AuthedTasksIndexRoute;
}

const AuthedTasksRouteRouteChildren: AuthedTasksRouteRouteChildren = {
  AuthedTasksTaskIdRoute: AuthedTasksTaskIdRoute,
  AuthedTasksNewRoute: AuthedTasksNewRoute,
  AuthedTasksIndexRoute: AuthedTasksIndexRoute,
};

const AuthedTasksRouteRouteWithChildren =
  AuthedTasksRouteRoute._addFileChildren(AuthedTasksRouteRouteChildren);

interface AuthedRouteRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren;
  AuthedTasksRouteRoute: typeof AuthedTasksRouteRouteWithChildren;
  AuthedProfileRoute: typeof AuthedProfileRoute;
  AuthedDebugStreamingSseRoute: typeof AuthedDebugStreamingSseRoute;
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedTasksRouteRoute: AuthedTasksRouteRouteWithChildren,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedDebugStreamingSseRoute: AuthedDebugStreamingSseRoute,
};

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
);

interface GuestRouteRouteChildren {
  GuestSigninRoute: typeof GuestSigninRoute;
  GuestSignupRoute: typeof GuestSignupRoute;
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestSigninRoute: GuestSigninRoute,
  GuestSignupRoute: GuestSignupRoute,
};

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  PrivacyRoute: PrivacyRoute,
  SignoutRoute: SignoutRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSseNotificationsRoute: ApiSseNotificationsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
