/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TermsRouteImport } from "./routes/terms";
import { Route as TasksRouteImport } from "./routes/tasks";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as SignoutRouteImport } from "./routes/signout";
import { Route as SigninRouteImport } from "./routes/signin";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as PrivacyRouteImport } from "./routes/privacy";
import { Route as HealthRouteImport } from "./routes/health";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as TasksIndexRouteImport } from "./routes/tasks/index";
import { Route as AdminIndexRouteImport } from "./routes/admin/index";
import { Route as TasksNewRouteImport } from "./routes/tasks/new";
import { Route as TasksTaskIdRouteImport } from "./routes/tasks/$taskId";
import { Route as DebugStreamingRouteImport } from "./routes/debug/streaming";
import { Route as DebugMonitoringRouteImport } from "./routes/debug/monitoring";
import { Route as AdminUsersIndexRouteImport } from "./routes/admin/users/index";
import { Route as AdminTasksIndexRouteImport } from "./routes/admin/tasks/index";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as AdminUsersUserIdRouteImport } from "./routes/admin/users/$userId";
import { Route as AdminTasksNewRouteImport } from "./routes/admin/tasks/new";
import { Route as AdminTasksTaskIdRouteImport } from "./routes/admin/tasks/$taskId";
import { Route as AdminEmailsWelcomeRouteImport } from "./routes/admin/emails/welcome";

const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any);
const TasksRoute = TasksRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => rootRouteImport,
} as any);
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any);
const SignoutRoute = SignoutRouteImport.update({
  id: "/signout",
  path: "/signout",
  getParentRoute: () => rootRouteImport,
} as any);
const SigninRoute = SigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any);
const HealthRoute = HealthRouteImport.update({
  id: "/health",
  path: "/health",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => TasksRoute,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRoute,
} as any);
const TasksNewRoute = TasksNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => TasksRoute,
} as any);
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: "/$taskId",
  path: "/$taskId",
  getParentRoute: () => TasksRoute,
} as any);
const DebugStreamingRoute = DebugStreamingRouteImport.update({
  id: "/debug/streaming",
  path: "/debug/streaming",
  getParentRoute: () => rootRouteImport,
} as any);
const DebugMonitoringRoute = DebugMonitoringRouteImport.update({
  id: "/debug/monitoring",
  path: "/debug/monitoring",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => AdminRoute,
} as any);
const AdminTasksIndexRoute = AdminTasksIndexRouteImport.update({
  id: "/tasks/",
  path: "/tasks/",
  getParentRoute: () => AdminRoute,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: "/users/$userId",
  path: "/users/$userId",
  getParentRoute: () => AdminRoute,
} as any);
const AdminTasksNewRoute = AdminTasksNewRouteImport.update({
  id: "/tasks/new",
  path: "/tasks/new",
  getParentRoute: () => AdminRoute,
} as any);
const AdminTasksTaskIdRoute = AdminTasksTaskIdRouteImport.update({
  id: "/tasks/$taskId",
  path: "/tasks/$taskId",
  getParentRoute: () => AdminRoute,
} as any);
const AdminEmailsWelcomeRoute = AdminEmailsWelcomeRouteImport.update({
  id: "/emails/welcome",
  path: "/emails/welcome",
  getParentRoute: () => AdminRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRouteWithChildren;
  "/health": typeof HealthRoute;
  "/privacy": typeof PrivacyRoute;
  "/profile": typeof ProfileRoute;
  "/signin": typeof SigninRoute;
  "/signout": typeof SignoutRoute;
  "/signup": typeof SignupRoute;
  "/tasks": typeof TasksRouteWithChildren;
  "/terms": typeof TermsRoute;
  "/debug/monitoring": typeof DebugMonitoringRoute;
  "/debug/streaming": typeof DebugStreamingRoute;
  "/tasks/$taskId": typeof TasksTaskIdRoute;
  "/tasks/new": typeof TasksNewRoute;
  "/admin/": typeof AdminIndexRoute;
  "/tasks/": typeof TasksIndexRoute;
  "/admin/emails/welcome": typeof AdminEmailsWelcomeRoute;
  "/admin/tasks/$taskId": typeof AdminTasksTaskIdRoute;
  "/admin/tasks/new": typeof AdminTasksNewRoute;
  "/admin/users/$userId": typeof AdminUsersUserIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/admin/tasks": typeof AdminTasksIndexRoute;
  "/admin/users": typeof AdminUsersIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/health": typeof HealthRoute;
  "/privacy": typeof PrivacyRoute;
  "/profile": typeof ProfileRoute;
  "/signin": typeof SigninRoute;
  "/signout": typeof SignoutRoute;
  "/signup": typeof SignupRoute;
  "/terms": typeof TermsRoute;
  "/debug/monitoring": typeof DebugMonitoringRoute;
  "/debug/streaming": typeof DebugStreamingRoute;
  "/tasks/$taskId": typeof TasksTaskIdRoute;
  "/tasks/new": typeof TasksNewRoute;
  "/admin": typeof AdminIndexRoute;
  "/tasks": typeof TasksIndexRoute;
  "/admin/emails/welcome": typeof AdminEmailsWelcomeRoute;
  "/admin/tasks/$taskId": typeof AdminTasksTaskIdRoute;
  "/admin/tasks/new": typeof AdminTasksNewRoute;
  "/admin/users/$userId": typeof AdminUsersUserIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/admin/tasks": typeof AdminTasksIndexRoute;
  "/admin/users": typeof AdminUsersIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/admin": typeof AdminRouteWithChildren;
  "/health": typeof HealthRoute;
  "/privacy": typeof PrivacyRoute;
  "/profile": typeof ProfileRoute;
  "/signin": typeof SigninRoute;
  "/signout": typeof SignoutRoute;
  "/signup": typeof SignupRoute;
  "/tasks": typeof TasksRouteWithChildren;
  "/terms": typeof TermsRoute;
  "/debug/monitoring": typeof DebugMonitoringRoute;
  "/debug/streaming": typeof DebugStreamingRoute;
  "/tasks/$taskId": typeof TasksTaskIdRoute;
  "/tasks/new": typeof TasksNewRoute;
  "/admin/": typeof AdminIndexRoute;
  "/tasks/": typeof TasksIndexRoute;
  "/admin/emails/welcome": typeof AdminEmailsWelcomeRoute;
  "/admin/tasks/$taskId": typeof AdminTasksTaskIdRoute;
  "/admin/tasks/new": typeof AdminTasksNewRoute;
  "/admin/users/$userId": typeof AdminUsersUserIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/admin/tasks/": typeof AdminTasksIndexRoute;
  "/admin/users/": typeof AdminUsersIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/health"
    | "/privacy"
    | "/profile"
    | "/signin"
    | "/signout"
    | "/signup"
    | "/tasks"
    | "/terms"
    | "/debug/monitoring"
    | "/debug/streaming"
    | "/tasks/$taskId"
    | "/tasks/new"
    | "/admin/"
    | "/tasks/"
    | "/admin/emails/welcome"
    | "/admin/tasks/$taskId"
    | "/admin/tasks/new"
    | "/admin/users/$userId"
    | "/api/auth/$"
    | "/admin/tasks"
    | "/admin/users";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/health"
    | "/privacy"
    | "/profile"
    | "/signin"
    | "/signout"
    | "/signup"
    | "/terms"
    | "/debug/monitoring"
    | "/debug/streaming"
    | "/tasks/$taskId"
    | "/tasks/new"
    | "/admin"
    | "/tasks"
    | "/admin/emails/welcome"
    | "/admin/tasks/$taskId"
    | "/admin/tasks/new"
    | "/admin/users/$userId"
    | "/api/auth/$"
    | "/admin/tasks"
    | "/admin/users";
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/health"
    | "/privacy"
    | "/profile"
    | "/signin"
    | "/signout"
    | "/signup"
    | "/tasks"
    | "/terms"
    | "/debug/monitoring"
    | "/debug/streaming"
    | "/tasks/$taskId"
    | "/tasks/new"
    | "/admin/"
    | "/tasks/"
    | "/admin/emails/welcome"
    | "/admin/tasks/$taskId"
    | "/admin/tasks/new"
    | "/admin/users/$userId"
    | "/api/auth/$"
    | "/admin/tasks/"
    | "/admin/users/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRoute: typeof AdminRouteWithChildren;
  HealthRoute: typeof HealthRoute;
  PrivacyRoute: typeof PrivacyRoute;
  ProfileRoute: typeof ProfileRoute;
  SigninRoute: typeof SigninRoute;
  SignoutRoute: typeof SignoutRoute;
  SignupRoute: typeof SignupRoute;
  TasksRoute: typeof TasksRouteWithChildren;
  TermsRoute: typeof TermsRoute;
  DebugMonitoringRoute: typeof DebugMonitoringRoute;
  DebugStreamingRoute: typeof DebugStreamingRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/terms": {
      id: "/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof TermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tasks": {
      id: "/tasks";
      path: "/tasks";
      fullPath: "/tasks";
      preLoaderRoute: typeof TasksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signout": {
      id: "/signout";
      path: "/signout";
      fullPath: "/signout";
      preLoaderRoute: typeof SignoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signin": {
      id: "/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof SigninRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy": {
      id: "/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/health": {
      id: "/health";
      path: "/health";
      fullPath: "/health";
      preLoaderRoute: typeof HealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tasks/": {
      id: "/tasks/";
      path: "/";
      fullPath: "/tasks/";
      preLoaderRoute: typeof TasksIndexRouteImport;
      parentRoute: typeof TasksRoute;
    };
    "/admin/": {
      id: "/admin/";
      path: "/";
      fullPath: "/admin/";
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/tasks/new": {
      id: "/tasks/new";
      path: "/new";
      fullPath: "/tasks/new";
      preLoaderRoute: typeof TasksNewRouteImport;
      parentRoute: typeof TasksRoute;
    };
    "/tasks/$taskId": {
      id: "/tasks/$taskId";
      path: "/$taskId";
      fullPath: "/tasks/$taskId";
      preLoaderRoute: typeof TasksTaskIdRouteImport;
      parentRoute: typeof TasksRoute;
    };
    "/debug/streaming": {
      id: "/debug/streaming";
      path: "/debug/streaming";
      fullPath: "/debug/streaming";
      preLoaderRoute: typeof DebugStreamingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/debug/monitoring": {
      id: "/debug/monitoring";
      path: "/debug/monitoring";
      fullPath: "/debug/monitoring";
      preLoaderRoute: typeof DebugMonitoringRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/users/": {
      id: "/admin/users/";
      path: "/users";
      fullPath: "/admin/users";
      preLoaderRoute: typeof AdminUsersIndexRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/tasks/": {
      id: "/admin/tasks/";
      path: "/tasks";
      fullPath: "/admin/tasks";
      preLoaderRoute: typeof AdminTasksIndexRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/users/$userId": {
      id: "/admin/users/$userId";
      path: "/users/$userId";
      fullPath: "/admin/users/$userId";
      preLoaderRoute: typeof AdminUsersUserIdRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/tasks/new": {
      id: "/admin/tasks/new";
      path: "/tasks/new";
      fullPath: "/admin/tasks/new";
      preLoaderRoute: typeof AdminTasksNewRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/tasks/$taskId": {
      id: "/admin/tasks/$taskId";
      path: "/tasks/$taskId";
      fullPath: "/admin/tasks/$taskId";
      preLoaderRoute: typeof AdminTasksTaskIdRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/emails/welcome": {
      id: "/admin/emails/welcome";
      path: "/emails/welcome";
      fullPath: "/admin/emails/welcome";
      preLoaderRoute: typeof AdminEmailsWelcomeRouteImport;
      parentRoute: typeof AdminRoute;
    };
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute;
  AdminEmailsWelcomeRoute: typeof AdminEmailsWelcomeRoute;
  AdminTasksTaskIdRoute: typeof AdminTasksTaskIdRoute;
  AdminTasksNewRoute: typeof AdminTasksNewRoute;
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute;
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute;
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminEmailsWelcomeRoute: AdminEmailsWelcomeRoute,
  AdminTasksTaskIdRoute: AdminTasksTaskIdRoute,
  AdminTasksNewRoute: AdminTasksNewRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute;
  TasksNewRoute: typeof TasksNewRoute;
  TasksIndexRoute: typeof TasksIndexRoute;
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksNewRoute: TasksNewRoute,
  TasksIndexRoute: TasksIndexRoute,
};

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HealthRoute: HealthRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SigninRoute: SigninRoute,
  SignoutRoute: SignoutRoute,
  SignupRoute: SignupRoute,
  TasksRoute: TasksRouteWithChildren,
  TermsRoute: TermsRoute,
  DebugMonitoringRoute: DebugMonitoringRoute,
  DebugStreamingRoute: DebugStreamingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
